const lessonsData = [
    { lessonTitle: 'Lesson Title 1', grade: 4, id: 1, summaryText: [{ character: "kotoz", events: ["event1", "event2", "event3 kotoz"] }, { character: "harry", events: ["event1", "event 2 harry"] }], summaryByDate: [{ date: '1/12/2000', events: ["eventdate1", "eventdate2"] }] },
    { lessonTitle: 'Lesson Title 2', grade: 4, id: 2, summaryText: [{ character: "kotoz", events: ["event1", "event2", "event3 kotoz"] }, { character: "harry", events: ["event1", "event 2 harry"] }], summaryByDate: [{ date: '1/12/2000', events: ["eventdate1", "eventdate2"] }] },
    { lessonTitle: 'Lesson Title 3', grade: 4, id: 3, summaryText: [{ character: "kotoz", events: ["event1", "event2", "event3 kotoz"] }, { character: "harry", events: ["event1", "event 2 harry"] }], summaryByDate: [{ date: '1/12/2000', events: ["eventdate1", "eventdate2"] }] },
    { lessonTitle: 'Lesson Title 4', grade: 4, id: 4, summaryText: [{ character: "kotoz", events: ["event1", "event2", "event3 kotoz"] }, { character: "harry", events: ["event1", "event 2 harry"] }], summaryByDate: [{ date: '1/12/2000', events: ["eventdate1", "eventdate2"] }] },
    { lessonTitle: 'Lesson Title 1', grade: 5, id: 5, summaryText: [{ character: "kotoz", events: ["event1", "event2", "event3 kotoz"] }, { character: "harry", events: ["event1", "event 2 harry"] }], summaryByDate: [{ date: '1/12/2000', events: ["eventdate1", "eventdate2"] }] },
    { lessonTitle: 'Lesson Title 2', grade: 5, id: 6, summaryText: [{ character: "kotoz", events: ["event1", "event2", "event3 kotoz"] }, { character: "harry", events: ["event1", "event 2 harry"] }], summaryByDate: [{ date: '1/12/2000', events: ["eventdate1", "eventdate2"] }] },
    { lessonTitle: 'Lesson Title 3', grade: 5, id: 7, summaryText: [{ character: "kotoz", events: ["event1", "event2", "event3 kotoz"] }, { character: "harry", events: ["event1", "event 2 harry"] }], summaryByDate: [{ date: '1/12/2000', events: ["eventdate1", "eventdate2"] }] },
    { lessonTitle: 'Lesson Title 1', grade: 6, id: 8, summaryText: [{ character: "kotoz", events: ["event1", "event2", "event3 kotoz"] }, { character: "harry", events: ["event1", "event 2 harry"] }], summaryByDate: [{ date: '1/12/2000', events: ["eventdate1", "eventdate2"] }] },
    { lessonTitle: 'Lesson Title 2', grade: 6, id: 9, summaryText: [{ character: "kotoz", events: ["event1", "event2", "event3 kotoz"] }, { character: "harry", events: ["event1", "event 2 harry"] }], summaryByDate: [{ date: '1/12/2000', events: ["eventdate1", "eventdate2"] }] }
];
export default lessonsData;